Repository hosu794/juniorstart-backend, pull requests merged in 2020-10, with the labels that each got.

#32 B14 job offers
  src/.gitignore
  src/main/java/com/juniorstart/juniorstart/controller/JobOfferController.java
  src/main/java/com/juniorstart/juniorstart/controller/UserController.java
  src/main/java/com/juniorstart/juniorstart/model/JobOffer.java
  src/main/java/com/juniorstart/juniorstart/model/JobOfferRequirements.java
  src/main/java/com/juniorstart/juniorstart/model/Technologies.java
  src/main/java/com/juniorstart/juniorstart/model/TechnologyType.java
  src/main/java/com/juniorstart/juniorstart/model/User.java
  src/main/java/com/juniorstart/juniorstart/payload/JobOfferRequest.java
  src/main/java/com/juniorstart/juniorstart/repository/JobOfferRepository.java
  src/main/java/com/juniorstart/juniorstart/repository/JobOfferRequirementsRepository.java
  src/main/java/com/juniorstart/juniorstart/repository/TechnologiesRepository.java
  src/main/java/com/juniorstart/juniorstart/service/JobOfferService.java
  src/main/resources/application.yml
  src/test/java/com/juniorstart/juniorstart/service/JobOfferServiceTest.java
Labels: enhancement

#41 B037 | Added multiple database configuration
  src/main/java/com/juniorstart/juniorstart/config/DatabasesConfig.java
  src/main/java/com/juniorstart/juniorstart/controller/UserController.java
  src/main/resources/application.yml
Labels: enhancement

#34 B004 | Technology filtering mentors v2
  pom.xml
  src/main/java/com/juniorstart/juniorstart/controller/UserProfileController.java
  src/main/java/com/juniorstart/juniorstart/model/User.java
  src/main/java/com/juniorstart/juniorstart/model/UserProfile.java
  src/main/java/com/juniorstart/juniorstart/model/UserRole.java
  src/main/java/com/juniorstart/juniorstart/model/UserTechnology.java
  src/main/java/com/juniorstart/juniorstart/payload/PagedResponse.java
  src/main/java/com/juniorstart/juniorstart/payload/UserRoleOrTechnologyRequest.java
  src/main/java/com/juniorstart/juniorstart/repository/UserProfileRepository.java
  src/main/java/com/juniorstart/juniorstart/service/UserProfileService.java
  src/main/java/com/juniorstart/juniorstart/util/AppConstants.java
  src/main/java/com/juniorstart/juniorstart/util/ValidatePageUtil.java
  src/test/java/com/juniorstart/juniorstart/service/UserProfileIntegrationTest.java
  src/test/java/com/juniorstart/juniorstart/service/UserProfileMockTest.java
Labels: enhancement

#42 B044 | Deleted secrets from application.yml
  src/main/resources/application.yml
Labels: Security, hacktoberfest-accepted

#43 B043 | Logger and Docker implementation
  .gitignore
  Dockerfile
  docker/docker-compose.yml
  docker/postgres_logs_db/Dockerfile-postgres_logs
  docker/postgres_logs_db/initdb.sql
  pom.xml
  src/main/resources/application.yml
  src/main/resources/logback.groovy
  src/test/java/com/juniorstart/juniorstart/email/MailTemplateCreatorTest.java
  src/test/java/com/juniorstart/juniorstart/service/AuthenticationServiceTest.java
  src/test/java/com/juniorstart/juniorstart/service/JobOfferServiceTest.java
  src/test/java/com/juniorstart/juniorstart/service/UserProfileIntegrationTest.java
  src/test/java/com/juniorstart/juniorstart/service/UserProfileMockTest.java
  src/test/resources/logback.groovy
Labels: enhancement, hacktoberfest-accepted
